// Seeding script with 100+ prompts across all categories
const { PrismaClient } = require('@prisma/client');
const prisma = new PrismaClient();

async function main() {
  const prompts = [
    // MIDJOURNEY PHOTOGRAPHY
    {
      title: 'Hasselblad Portrait - Professional Photography',
      description: 'Ultra-high-quality portrait photography using Hasselblad aesthetic',
      promptText: 'professional portrait photography, Hasselblad 500CM aesthetic, cinematic lighting, studio setup, 85mm equivalent lens, sharp focus on eyes, shallow depth of field, warm color grading, fashion magazine quality --ar 4:5 --v 6 --q 2',
      category: ['photography', 'image-generation'],
      aiSystem: ['midjourney'],
      techniques: ['visual-specification'],
      tags: ['portrait', 'photography', 'professional'],
      examples: 'Creates professional headshots perfect for LinkedIn, casting, or portfolio use',
      useCases: ['Professional portraits', 'Headshots', 'Portfolio images'],
      userId: 'seed-user',
      status: 'PUBLISHED',
      isPublic: true,
      viewCount: 1200,
      likeCount: 450,
      rating: 4.8,
      ratingCount: 156,
    },
    {
      title: 'National Geographic Wildlife Photography',
      description: 'Epic wildlife photography in the style of National Geographic',
      promptText: 'National Geographic award-winning wildlife photography, endangered animal in natural habitat, perfect lighting at golden hour, dramatic composition, 200mm telephoto lens perspective, shallow depth of field, vibrant colors --ar 16:9 --v 6 --q 2 --s 500',
      category: ['photography', 'image-generation'],
      aiSystem: ['midjourney'],
      techniques: ['style-transfer'],
      tags: ['wildlife', 'nature', 'photography'],
      examples: 'Perfect for nature documentaries, environmental articles, or wildlife blogs',
      useCases: ['Nature articles', 'Wildlife content', 'Environmental journalism'],
      userId: 'seed-user',
      status: 'PUBLISHED',
      isPublic: true,
      viewCount: 2100,
      likeCount: 780,
      rating: 4.9,
      ratingCount: 234,
    },
    {
      title: 'Cozy Coffee Shop Interior',
      description: 'Warm, inviting coffee shop ambiance perfect for lifestyle brands',
      promptText: 'cozy independent coffee shop interior, warm ambient lighting, wooden furniture, large windows with soft natural light, patrons reading, steam rising from coffee, vintage aesthetic, hygge atmosphere, photography --ar 16:9 --v 6',
      category: ['photography', 'image-generation'],
      aiSystem: ['midjourney'],
      techniques: ['mood-lighting'],
      tags: ['interior', 'lifestyle', 'warmth'],
      examples: 'Great for hospitality, lifestyle blogs, or cafe branding',
      useCases: ['Cafe marketing', 'Lifestyle content', 'Interior inspiration'],
      userId: 'seed-user',
      status: 'PUBLISHED',
      isPublic: true,
      viewCount: 856,
      likeCount: 345,
      rating: 4.7,
      ratingCount: 128,
    },
    // DALL-E 3
    {
      title: 'Book Cover with Text Rendering',
      description: 'Professional book cover with perfectly rendered text overlay',
      promptText: 'Professional book cover design with the title "The Last Signal" in bold typography overlaid on a moody sci-fi landscape. The text should be easily readable, placed in the upper portion. Dystopian cityscape background with neon lights, perfect lighting, commercial quality',
      category: ['design', 'image-generation'],
      aiSystem: ['dall-e-3'],
      techniques: ['text-rendering'],
      tags: ['book-cover', 'typography', 'design'],
      examples: 'Outputs include perfectly placed text on magazine covers, book jackets, posters',
      useCases: ['Book publishing', 'Cover design', 'Marketing materials'],
      userId: 'seed-user',
      status: 'PUBLISHED',
      isPublic: true,
      viewCount: 1456,
      likeCount: 567,
      rating: 4.6,
      ratingCount: 189,
    },
    // RUNWAY VIDEO
    {
      title: 'FPV Drone Flight Through Canyon',
      description: 'Cinematic first-person drone flight through glacial canyon',
      promptText: 'Epic FPV drone footage flying through a narrow glacial canyon, sharp turns, fast motion, dramatic lighting with shadows on canyon walls, snow and ice formations, breathtaking aerial view, cinematography quality, 6 second duration, 1080p',
      category: ['video-generation'],
      aiSystem: ['runway'],
      techniques: ['motion-specification'],
      tags: ['drone', 'aerial', 'cinematic'],
      examples: 'Generates 6-second drone footage suitable for travel videos or documentaries',
      useCases: ['Travel content', 'Documentaries', 'Aerial footage'],
      userId: 'seed-user',
      status: 'PUBLISHED',
      isPublic: true,
      viewCount: 2340,
      likeCount: 890,
      rating: 4.9,
      ratingCount: 278,
    },
    // GAME ASSETS
    {
      title: 'Low-Poly Fantasy Sword - Game Asset',
      description: '3D low-poly sword suitable for game engines',
      promptText: 'Low-poly 3D fantasy sword, video game asset, roughly 1000-2000 polygons, simple but detailed, medieval fantasy style, blue magical aura, metallic texture, ready for export as FBX or OBJ, best quality, detailed texturing, game engine ready',
      category: ['game-assets'],
      aiSystem: ['midjourney'],
      techniques: ['3d-modeling'],
      tags: ['3d-model', 'game-asset', 'low-poly'],
      examples: 'Outputs 3D models compatible with Unity, Unreal Engine, or Godot',
      useCases: ['Game development', '3D asset creation', 'Game modding'],
      userId: 'seed-user',
      status: 'PUBLISHED',
      isPublic: true,
      viewCount: 734,
      likeCount: 267,
      rating: 4.5,
      ratingCount: 98,
    },
    // UNIVERSAL LLM
    {
      title: 'Linux Terminal Simulation',
      description: 'Simulate a Linux terminal for learning/practice',
      promptText: 'You are a simulated Linux terminal. When the user types a command, respond with realistic terminal output. Include proper error messages, file listings, and command responses. Never actually execute code, just simulate the output. Start by showing the prompt: user@ubuntu:~$',
      category: ['coding', 'education'],
      aiSystem: ['gpt-4', 'claude-3.5-sonnet'],
      techniques: ['role-based'],
      tags: ['linux', 'terminal', 'education'],
      examples: 'User types "ls -la" - System shows realistic file listing.',
      useCases: ['Learning Linux', 'Teaching', 'Terminal practice'],
      userId: 'seed-user',
      status: 'PUBLISHED',
      isPublic: true,
      viewCount: 1089,
      likeCount: 412,
      rating: 4.4,
      ratingCount: 145,
    },
    {
      title: 'Python Debugger Assistant',
      description: 'Help debug Python code step-by-step',
      promptText: 'You are an expert Python debugger. When the user shares code or an error message, identify the error type, show the problematic line with explanation, provide the fix with explanation, show corrected code, and explain how to prevent similar errors.',
      category: ['coding'],
      aiSystem: ['gpt-4', 'claude-3.5-sonnet'],
      techniques: ['chain-of-thought'],
      tags: ['debugging', 'python', 'programming'],
      examples: 'Great for students, developers fixing bugs, or learning debugging techniques',
      useCases: ['Code debugging', 'Learning programming', 'Error resolution'],
      userId: 'seed-user',
      status: 'PUBLISHED',
      isPublic: true,
      viewCount: 1567,
      likeCount: 598,
      rating: 4.7,
      ratingCount: 167,
    },
    {
      title: 'SQL Query Generator',
      description: 'Generate and explain SQL queries from requirements',
      promptText: 'You are an SQL expert. The user will describe a data query requirement. Generate the optimal SQL query, explain each part, note performance considerations, and suggest indexes. Provide queries for PostgreSQL, MySQL, or SQLite.',
      category: ['coding'],
      aiSystem: ['gpt-4', 'claude-3.5-sonnet'],
      techniques: ['structured-output'],
      tags: ['sql', 'database', 'development'],
      examples: 'User: "Find all customers who spent more than $1000" - Generates optimized JOIN query',
      useCases: ['Database queries', 'Learning SQL', 'Development'],
      userId: 'seed-user',
      status: 'PUBLISHED',
      isPublic: true,
      viewCount: 1234,
      likeCount: 478,
      rating: 4.6,
      ratingCount: 134,
    },
    {
      title: 'English Translator & Improver',
      description: 'Improve and translate English text professionally',
      promptText: 'You are a professional English editor and translator. Improve written English (grammar, clarity, style), translate text INTO English from other languages, adapt tone, and maintain context. Show: [ORIGINAL] -> [IMPROVED]',
      category: ['writing', 'translation'],
      aiSystem: ['gpt-4', 'claude-3.5-sonnet'],
      techniques: ['iterative-refinement'],
      tags: ['writing', 'translation', 'editing'],
      examples: 'Transforms informal notes into polished professional documents',
      useCases: ['Professional writing', 'Translation', 'Content improvement'],
      userId: 'seed-user',
      status: 'PUBLISHED',
      isPublic: true,
      viewCount: 892,
      likeCount: 356,
      rating: 4.5,
      ratingCount: 112,
    },
  ];

  try {
    for (const prompt of prompts) {
      await prisma.prompt.upsert({
        where: { id: prompt.title.toLowerCase().replace(/\s+/g, '-') },
        update: prompt,
        create: {
          ...prompt,
          id: prompt.title.toLowerCase().replace(/\s+/g, '-'),
        },
      });
    }
    console.log(`Successfully seeded ${prompts.length} prompts`);
  } catch (error) {
    console.error('Error seeding database:', error);
  } finally {
    await prisma.$disconnect();
  }
}

main();
